site_name: CHBH User Handbook
site_url: https://ajquinn.github.io/chbh-on-bear/

repo_name: CHBH-on-BEAR
repo_url: https://github.com/AJQuinn/chbh-on-bear
edit_uri: blob/main/docs

markdown_extensions:
  - toc:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  features:
    - content.code.copy
  logo: images/CHBH_logo.jpg
  favicon: images/CHBH_logo.jpg
  
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - MRI:
    - mri/index.md
    - Hardware:
      - The MRI Scanner: mri/hardware/scanner.md
      - Stimulus Equipment: mri/hardware/stimulus_equipment.md
      - Troubleshooting: mri/hardware/troubleshooting.md
    - Analysis Tools:
      - fMRIPrep: mri/analysis/fmriprep.md
      - FreeSurfer: mri/analysis/freesurfer.md
      - FSL: mri/analysis/fsl.md
      - SPM: mri/analysis/spm.md
      - spant: mri/analysis/spant.md
    - Mock MRI:
      - Technical Info: mri/mockmri/mockmri.md
  - MEG:
    - meg/index.md
    - Hardware:
      - MEG System: meg/hardware/meg.md
      - MEG Safety: meg/hardware/safety.md
      - MEG Contraindications: meg/hardware/contraindications.md
      - How to open the MSR: meg/hardware/msr.md
      - MSR Dimensions: meg/hardware/dimensions.md
      - The IHR: meg/hardware/ihr.md
      - LabJack: meg/hardware/meg-labjack.md
      - SIGGI II Impedance Meter: meg/pdfs/SIGGI_II_User_Manual.pdf
      - EyeLink 1000 Plus Operations Guide: meg/acquisition/eyelink_operations_guide.md
      - Copying EyeLink EDF Files: meg/acquisition/copying_edf_files.md
      - EyeLink Demo Code: meg/acquisition/eyelink_demo.md
      - Charging EyeLink batteries: meg/acquisition/charging_eyelink_batteries.md
      - EyeLink Settings: meg/acquisition/eyelink_settings.md
      - EyeLink Analog Output: meg/acquisition/eyelink_analog_output.md
      - X-Rite i1Display Pro: meg/hardware/x_rite_i1_display_pro.md
    - Acquisition:
      - MEG Checklist: meg/acquisition/meg-acquisition-checklist.md
      - Noisy Channels: meg/acquisition/noisy_channels.md
      - Fixing Noisy Channels: meg/acquisition/to_fix_noisy_channels.md
      - Noisy Data: meg/acquisition/noisy_data.md
      - Perform a "RAP": meg/acquisition/rap.md
      - Restart Acquisition: meg/acquisition/restart_acquisition.md
      - Metal items Checklist: meg/pdfs/Metal_items_checklist.pdf
      - Moving the Gantry: meg/acquisition/moving-the-gantry.md
      - Copying MEG data: meg/acquisition/copying_meg_data.md
      - MEG Consumables: meg/acquisition/meg-consumables.md
      - Tidying Up: meg/acquisition/tidying_up.md
      - Cleaning EEG Caps: meg/acquisition/cleaning_eeg_caps.md
      - Audio Delay Testing: meg/acquisition/audio_delay_testing.md
      - MISC Channels: meg/acquisition/misc_channels.md
    - Lab Safety:
      - Procedures: meg/labsafety/labsafety.md
    - Stimulus Presentation:
      - Stimulus Hardware Layout: meg/pdfs/MEG_Stimulus_Hardware_Layout.pdf
      - VPixx Projector: meg/stimulus/propixx.md
    - Analysis Tools:
      - MNE-Python: meg/analysis/mne.md
  - Eye-tracking:
    - eye-tracking/index.md
  - EEG:
    - eeg/index.md
    - Hardware:
      - The EEG System: eeg/hardware/eeg.md
    - Acquisition:
      - Setting up your Experiment: eeg/acquisition/preparing_code_for_EEG.md
      - EEG Acquisition Checklist: eeg/acquisition/how_to_acquire.md
    - Analysis Tools:
      - FieldTrip: eeg/analysis/fieldtrip.md
  - EEG-fMRI:
    - eeg-fmri/index.md
  - Brain Stimulation:
    - brainstim/index.md
    - FUS:
      - Equip: brainstim/FUS/equip.md
      - k-Plan: brainstim/FUS/kplan.md
      - Calibration: brainstim/FUS/calib.md
    - TMS: brainstim/tms.md
  - Behaviour:
    - behaviour/index.md
    - Technical:
      - Cubicles: behaviour/technical/cubicles.md
      - Common Experimental Platform: behaviour/technical/cep.md
      - Troubleshooting: behaviour/technical/troubleshooting.md
  - Sleep:
    - sleep/index.md
  - fNIRS:
    - fnirs/index.md
  - Software on BEAR:
    - software/index.md
    - Conda: software/conda.md
    - Containers: software/containers.md
    - MATLAB: software/matlab.md
    - Python: software/python.md
    - R: software/R.md
  - Making a contribution : making_a_contribution.md
  - FAQs: faqs.md
